version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pocDataLoad"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16ges88ae2m1e"
s3_prefix = "pocDataLoad"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
